# Generated by Django 2.1.1 on 2018-09-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_sixth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='company',
            field=models.CharField(choices=[('google', 'Google'), ('yandex', 'Yandex'), ('itvdn', 'Itvdn'), ('epam', 'Epam')], max_length=150),
        ),
    ]
