# Generated by Django 2.1.1 on 2018-09-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=500, verbose_name='Текст статьи')),
            ],
        ),
        migrations.CreateModel(
            name='Author1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия автора')),
                ('city', models.CharField(choices=[('Moscow', 'Москва'), ('Saint-Petersburgh', 'Санкт-Петербург'), ('Novgorod', 'Новогород'), ('Tomsk', 'Томск')], help_text='Выберите город со списка', max_length=200, verbose_name='Город')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_fifth.Author1', verbose_name='Автор статьи'),
        ),
    ]
